FROM python:3.9-slim

WORKDIR /workspace

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc g++ && \
    pip install --no-cache-dir flake8 && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-deps tritonclient[grpc]

COPY . .


EXPOSE 80
CMD ["python", "app.py"]