"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RKSLI9fnzZ-aPNC1o3fEy4eMsCY9s-Xt
"""

import pandas as pd
from sklearn.cluster import KMeans
import numpy as np

data = pd.read_csv('tourism_dataset.csv')

def filter_by_preferences(df, country=None, category=None, min_rating=4.0, accommodation_needed=True):
    filtered_data = df

    if country:
        filtered_data = filtered_data[filtered_data['Country'] == country]

    if category:
        filtered_data = filtered_data[filtered_data['Category'] == category]

    filtered_data = filtered_data[filtered_data['Rating'] >= min_rating]

    if accommodation_needed:
        filtered_data = filtered_data[filtered_data['Accommodation_Available'] == "Yes"]

    return filtered_data

def apply_clustering(df, n_clusters=5):
    if df.empty:
        print("Нет данных для кластеризации после фильтрации.")
        return df

    features = df[['Visitors', 'Rating', 'Revenue']].copy()

    features.fillna(features.mean(), inplace=True)

    kmeans = KMeans(n_clusters=n_clusters, random_state=42)
    df['Cluster'] = kmeans.fit_predict(features)

    return df

def get_recommendations(preferences, budget=None, n_clusters=5):
    filtered_data = filter_by_preferences(data,
     country=preferences.get('country'),
     category=preferences.get('category'),
    min_rating=preferences.get('min_rating', 4.0),
      accommodation_needed=preferences.get('accommodation_needed', True))

    if budget:
        filtered_data = filtered_data[filtered_data['Revenue'] <= budget]

    if filtered_data.empty:
        print("Нет данных, соответствующих заданным критериям.")
        return pd.DataFrame() 

    clustered_data = apply_clustering(filtered_data, n_clusters=n_clusters)

    if clustered_data.empty:
        return pd.DataFrame() 
    best_cluster = clustered_data.groupby('Cluster')['Rating'].mean().idxmax()
    recommendations = clustered_data[clustered_data['Cluster'] == best_cluster]

    recommendations = recommendations.sort_values(by=['Rating', 'Visitors'], ascending=False)

    return recommendations

user_preferences = {
    'country': 'China',
    'category': 'Historical',
    'min_rating': 2.0,
    'accommodation_needed': True
}

user_budget = 1000000.0

recommendations = get_recommendations(user_preferences, user_budget, n_clusters=5)

if not recommendations.empty:
    print(recommendations[['Location', 'Country', 'Category', 'Rating', 'Revenue', 'Cluster']])
else:
    print("Рекомендаций нет.")